CREATE TABLE application.reaction_types (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    label varchar(80) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    display_order smallint NOT NULL,
    CONSTRAINT reaction_types_order_ck CHECK (display_order > 0)
);

CREATE TABLE application.publication_reactions (
    publication_id uuid NOT NULL REFERENCES application.publications(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES application.users(id) ON DELETE CASCADE,
    reaction_type_id smallint NOT NULL REFERENCES application.reaction_types(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    PRIMARY KEY (publication_id, user_id, reaction_type_id)
);

CREATE TABLE application.saved_publications (
    user_id uuid NOT NULL REFERENCES application.users(id) ON DELETE CASCADE,
    publication_id uuid NOT NULL REFERENCES application.publications(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    PRIMARY KEY (user_id, publication_id)
);
