CREATE TABLE application.report_reasons (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    label varchar(120) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    display_order smallint NOT NULL,
    CONSTRAINT report_reasons_order_ck CHECK (display_order > 0)
);

CREATE TABLE application.moderation_cases (
    id uuid PRIMARY KEY,
    publication_id uuid NOT NULL REFERENCES application.publications(id) ON DELETE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    report_count_at_open integer NOT NULL,
    opened_at timestamptz NOT NULL DEFAULT now(),
    reviewed_by uuid REFERENCES application.users(id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    decision_note text,
    CONSTRAINT moderation_cases_status_ck CHECK (status IN ('PENDING', 'KEPT', 'HIDDEN', 'REMOVED')),
    CONSTRAINT moderation_cases_count_ck CHECK (report_count_at_open > 0),
    CONSTRAINT moderation_cases_note_length_ck CHECK (decision_note IS NULL OR char_length(decision_note) <= 2000),
    CONSTRAINT moderation_cases_review_ck CHECK (
        (status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (status <> 'PENDING' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    ),
    CONSTRAINT moderation_cases_decision_note_ck CHECK (
        status IN ('PENDING', 'KEPT') OR (decision_note IS NOT NULL AND char_length(btrim(decision_note)) > 0)
    )
);

CREATE TABLE application.reports (
    id uuid PRIMARY KEY,
    publication_id uuid NOT NULL REFERENCES application.publications(id) ON DELETE CASCADE,
    reporter_id uuid NOT NULL REFERENCES application.users(id) ON DELETE CASCADE,
    reason_id smallint NOT NULL REFERENCES application.report_reasons(id) ON DELETE RESTRICT,
    description text,
    moderation_case_id uuid REFERENCES application.moderation_cases(id) ON DELETE SET NULL,
    resolution varchar(20) NOT NULL DEFAULT 'PENDING',
    created_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    CONSTRAINT reports_resolution_ck CHECK (resolution IN ('PENDING', 'UPHELD', 'REJECTED')),
    CONSTRAINT reports_description_length_ck CHECK (description IS NULL OR char_length(description) <= 1000),
    CONSTRAINT reports_resolved_at_ck CHECK (
        (resolution = 'PENDING' AND resolved_at IS NULL)
        OR
        (resolution <> 'PENDING' AND resolved_at IS NOT NULL)
    )
);

CREATE TABLE application.user_notifications (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES application.users(id) ON DELETE CASCADE,
    type varchar(40) NOT NULL,
    moderation_case_id uuid REFERENCES application.moderation_cases(id) ON DELETE SET NULL,
    publication_id uuid REFERENCES application.publications(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    read_at timestamptz,
    deleted_at timestamptz,
    CONSTRAINT user_notifications_type_ck CHECK (type IN ('REPORT_REJECTED_WARNING')),
    CONSTRAINT user_notifications_origin_ck CHECK (moderation_case_id IS NOT NULL)
);
